name: Autograding Tests
'on':
- push
- repository_dispatch 
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Verificacao GIT
      id: validate-git
      uses: webtech-network/web-code-autograding/actions/command-grader-action@v2
      with:
        test-name: Verificacao GIT
        command: validateGITRepo
        command-type: function
        weight: 20
        timeout: 10
        max-score: 100
    - name: Verificacao HTML
      id: validate-html
      uses: webtech-network/web-code-autograding/actions/command-grader-action@v2
      with:
        test-name: Verificacao HTML
        command: validateHTMLFile
        command-type: function
        weight: 20
        timeout: 10
        max-score: 100
    - name: Verificacao CSS
      id: validate-css
      uses: webtech-network/web-code-autograding/actions/command-grader-action@v2 
      with:
        test-name: Verificacao CSS
        command: validateCSSFile
        command-type: function
        weight: 20
        timeout: 10
        max-score: 100
    - name: Validate JS
      id: validate-js
      uses: webtech-network/web-code-autograding/actions/command-grader-action@v2
      with:
        test-name: Verificacao JS
        command: validateJSFile
        command-type: function
        weight: 40
        timeout: 10
        max-score: 100
    - name: Relatorio Final
      uses: webtech-network/web-code-autograding/actions/reporter-grader-action@v1
      env:
        VALIDATE-GIT_RESULTS: "${{steps.validate-git.outputs.result}}"
        VALIDATE-HTML_RESULTS: "${{steps.validate-html.outputs.result}}"
        VALIDATE-CSS_RESULTS: "${{steps.validate-css.outputs.result}}"
        VALIDATE-JS_RESULTS: "${{steps.validate-js.outputs.result}}"
      with:
        runners: validate-git,validate-html,validate-css,validate-js